//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.01.14 at 03:22:09 PM MSK 
//


package com.javatr.entity.gem;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.javatr.entity.gem package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Gem_QNAME = new QName("http://www.javatr.com/entity/gem", "gem");
    private final static QName _VisualParameters_QNAME = new QName("http://www.javatr.com/entity/gem", "visualParameters");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.javatr.entity.gem
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Gem }
     * 
     */
    public Gem createGem() {
        return new Gem();
    }

    /**
     * Create an instance of {@link VisualParameters }
     * 
     */
    public VisualParameters createVisualParameters() {
        return new VisualParameters();
    }

    /**
     * Create an instance of {@link Gems }
     * 
     */
    public Gems createGems() {
        return new Gems();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Gem }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Gem }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.javatr.com/entity/gem", name = "gem")
    public JAXBElement<Gem> createGem(Gem value) {
        return new JAXBElement<Gem>(_Gem_QNAME, Gem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VisualParameters }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VisualParameters }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.javatr.com/entity/gem", name = "visualParameters")
    public JAXBElement<VisualParameters> createVisualParameters(VisualParameters value) {
        return new JAXBElement<>(_VisualParameters_QNAME, VisualParameters.class, null, value);
    }

}
